services:
  playdate:
    image: playdate
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - action: rebuild
          path: .
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      # uncomment to enable persisting database across restarts
      # - ./postgres:/var/lib/postgresql/data
      - ./postgres/entrypoint/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

# volumes:
#   postgres: 
