services:
  playdate:
    image: playdate
    build: ./
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres