services:
  playdate:
    image: playdate
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: .
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: playdate
      POSTGRES_PASSWORD: playdate
      POSTGRES_DB: playdate
    ports:
      - 5432:5432
    volumes:
      # - ./postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

# volumes:
#   postgres: 
