-- This file is only executed on the initialization of the docker postgres container
CREATE TABLE example (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  column1 varchar(20),
  column2 integer
)

