# .github/workflows/release-webhook.yml

name: Release Webhook Notification (Coolify)

# This workflow runs when a new release is published.
on:
  release:
    types: [published] # Trigger only when a release is published

jobs:
  notify_coolify:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:

      # pulled from: https://github.com/coollabsio/coolify/discussions/2924#discussioncomment-11196215
      - name: Pin the sha version within Coolify
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{secrets.COOLIFY_URL}}/api/v1/applications/${{secrets.COOLIFY_APP_ID}}
          method: PATCH
          bearerToken: ${{secrets.COOLIFY_API_KEY}}
          data: >-
            {
            "git_commit_sha": "${{github.sha}}"
            }

      - name: Trigger Coolify deployment via webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{secrets.COOLIFY_URL}}/api/v1/deploy?uuid=${{secrets.COOLIFY_APP_ID}}&force=false
          method: GET
          bearerToken: ${{secrets.COOLIFY_API_KEY}}
